import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* App Layout */}
        <div className="min-h-dvh grid grid-rows-[auto_1fr_auto]">
          <header className="h-[88px] bg-slate-700 p-2">header</header>
          <main>
            <div>{children}</div>
          </main>

          <footer>footer</footer>
        </div>
      </body>
    </html>
  );
}
